name: Build and deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.chromopuncture-suisse.ch
          username: oo7ed_sarah
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./